server:
  port: 8083

springdoc:
  api-docs:
    path: /api-docs

spring:
  codec:
    max-in-memory-size: 10MB
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: smartbsmartb

fs:
  url: http://localhost:8090
  auth:
    url: https://auth.dev.connect.smart-b.io
    realm: sb-dev
    clientId: tr-smartb-registry-script-api-key
    clientSecret: 703ece3d-82bc-4747-8840-96c1c3431079
