# https://registry.trace.komune.io/projects/e53f091c-bb37-4840-ad82-b16c65224f44

### projectPage
POST https://trace.komune.io/ver/projectPage
Content-Type: application/json

{}

### projectGet
POST https://trace.komune.io/ver/projectGet
Content-Type: application/json

{
  "id": "{{projectId}}"
}

### assetTransactionPage
POST https://trace.komune.io/ver/assetTransactionPage
Content-Type: application/json

{
  "projectId": "8e7734b0-b50a-42b2-9826-757ba546c48c"
}

### OAuth2 Token Phease
POST https://auth.connect.komune.io/realms/sb-dev/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{offseter_clientId}}&client_secret={{offseter_clientSecret}}

> {% client.global.set("offseter_accessToken", response.body.access_token); %}

### assetOffset
POST https://trace.komune.io/ver/assetOffset
Content-Type: application/json
Authorization: Bearer {{offseter_accessToken}}

{
  "poolId": "{{poolId}}",
  "from": "CleanChain",
  "to": "0x5f5Afce1f980cBae2cEaf7Ec1696b0AEb8dE0366",
  "quantity": 20
}
