services:

  im-config:
    image: docker.io/komune/im-script:0.21.0-SNAPSHOT
    container_name: im-config-tmp
    environment:
      - im_script_space_auth_serverUrl=http://im-keycloak:8080 # local
      - im_script_space_auth_clientId=im-root-client # local
      - im_script_space_auth_clientSecret=secret # local
#      - im_script_space_auth_serverUrl=https://auth.connect.100m.kosmio.dev # dev
#      - im_script_space_auth_clientId=im-root-client # dev
#      - im_script_space_auth_clientSecret=692246df7005a43aa57f95b651400af5 # dev
#      - im_script_space_auth_serverUrl=https://auth.connect.wiki.preprod.objectif100m.org # preprod
#      - im_script_space_auth_clientId=im-root-client # preprod
#      - im_script_space_auth_clientSecret=7aaa7a6b7607f6e16df007709f94fd62 # preprod
      - im_script_space_jsonConfig=file:/tmp/space-config.json
    volumes:
      - ./space-config_tmp.json:/tmp/space-config.json
    networks:
      - net

networks:
  net:
    name: registry-local-network
    external: true
