server:
  port: 1000

logging:
  level:
    root: INFO

registry:
  script:
    retry:
      max: 5
      delayMillis: 10000
    init:
      auth:
        realmId: registry-local
        url: https://auth.connect.100m.kosmio.dev
      im:
        url: https://connect.100m.kosmio.dev/im
      cccev:
        url: https://connect.100m.kosmio.dev/cccev
      registry:
        url:  https://100m.kosmio.dev/api
      admin:
        name: Komune
        clientId: tr-registry-script-api
        clientSecret: secret
      flag:
        control: false
        data: true
        project: false
      nbProject: 25

---
spring:
  config:
    activate:
      on-profile: dev
