server:
  port: 1000

logging:
  level:
    root: INFO

registry:
  script:
    retry:
      max: 5
      delayMillis: 10000
    init:
      auth:
        realmId: registry-local
        url: http://localhost:8080
      im:
        url: http://localhost:8009
      cccev:
        url: http://localhost:8083
      registry:
        url: http://localhost:8070
      orchestrator:
        name: Komune
        clientId: tr-registry-script-api
        clientSecret: secret
      nbProject: 25

---
spring:
  config:
    activate:
      on-profile: dev
