server:
  port: 1000

registry:
  script:
    retry:
      max: 5
      delayMillis: 10000
    init:
      auth:
        realmId: sb-dev
        url: https://auth.dev.connect.komune.io
      im:
        url: http://dev.connect.komune.io/im
      cccev:
        url: http://localhost:8083
#      registry:
#        url: https://localhost:8070/ver
      orchestrator:
        name: Smartb
        clientId: tr-registry-script-api
        clientSecret: 703ece3d-82bc-4747-8840-96c1c3431079
      nbProject: 25

---
spring:
  config:
    activate:
      on-profile: dev
