import {
    alluvialdiagram,
    arcdiagram,
    barchartmultiset,
    barchartstacked,
    beeswarm,
    boxplot,
    bubblechart,
    bumpchart,
    chorddiagram,
    circlepacking,
    circularDendrogram,
    contourPlot,
    convexHull,
    dendrogram,
    ganttChart,
    hexagonalBinning,
    horizongraph,
    matrixplot,
    parallelcoordinates,
    radarchart,
    sankeydiagram,
    slopechart,
    streamgraph,
    sunburst,
    treemap,
    violinplot,
    voronoidiagram,
    voronoitreemap,
} from '@rawgraphs/rawgraphs-charts'

import { calendarHeatmap } from '@rawgraphs/rawgraphs-calendar-heatmap'
import PieChart from "./Chart/PieChart";
import BarChart from "./Chart/BarChart";
import LineChart from "./Chart/LineChart";

// New charts, not included into first release.
// Comment at necessity.
export const charts = [
    PieChart,
    BarChart,
    LineChart,
    alluvialdiagram,
    arcdiagram,
    barchartmultiset,
    barchartstacked,
    beeswarm,
    boxplot,
    bubblechart,
    bumpchart,
    calendarHeatmap,
    chorddiagram,
    circlepacking,
    circularDendrogram,
    contourPlot,
    convexHull,
    dendrogram,
    ganttChart,
    hexagonalBinning,
    horizongraph,
    matrixplot,
    parallelcoordinates,
    radarchart,
    sankeydiagram,
    slopechart,
    streamgraph,
    sunburst,
    treemap,
    violinplot,
    voronoidiagram,
    voronoitreemap,
]
