version: "3.8"

services:
  traefik:
    image: traefik:v3.3
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--accesslog=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt-resolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt-resolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt-resolver.acme.email=contact@kosmio.dev"
      - "--certificatesresolvers.letsencrypt-resolver.acme.storage=/letsencrypt/acme.json"
#      - "--certificatesresolvers.letsencrypt-resolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: Host(`${HOST_NAME_DASHBOARD}`)
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls.certresolver: letsencrypt-resolver
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: "${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
    default:
      name: ${DOCKER_NETWORK}
      external: true

volumes:
  traefik-certificates:
    driver: local
