services:

  redis:
    image: redis/redis-stack:7.2.0-v13
    env_file:
      - .env_dev
    environment:
      REDISEARCH_ARGS: MINPREFIX 1 MAXPREFIXEXPANSIONS 1000
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
