services:

  fs-gateway:
    container_name: fs-gateway
    image: ${DOCKER_REPOSITORY}fs-gateway:${CONNECT_FS_VERSION}
    env_file:
      - .env_dev
    environment:
      - f2_tenant_issuer-base-uri=${KC_URL}
      - fs_s3_internal-url=http://minio:9000
      - fs_s3_external-url=http://localhost:9000
      - fs_s3_bucket=certification
      - fs_init_buckets=certification
#      - fs_kb_url=${KB_HOST_NAME}
    labels:
      traefik.enable: "true"
      traefik.http.services.fs-gateway.loadbalancer.server.port: 8090
      traefik.http.routers.fs-gateway.rule: Host(`connect.100m.kosmio.dev`) && PathPrefix(`/fs`)
      traefik.http.routers.fs-gateway.entrypoints: websecure
      traefik.http.routers.fs-gateway.tls.certresolver: myresolver
      traefik.http.middlewares.api-strip-prefix.stripprefix.prefixes: /fs
      traefik.http.routers.fs-gateway.middlewares: api-strip-prefix
      traefik.docker.network: ${DOCKER_NETWORK}
    ports:
      - "8090:8090"
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
