services:
  minio:
    image: minio/minio:RELEASE.2022-02-26T02-54-46Z.fips
    container_name: minio
    env_file:
      - build/config/.env_dev
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_SERVER_URL=http://minio:9000
      - MINIO_BROWSER=on
    command: server /data --console-address ":9003"
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9003:9003"
    volumes:
      - minio:/data
    networks:
      - net

volumes:
  minio:

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
