services:

  cccev-gateway:
    image: ${DOCKER_REPOSITORY}cccev-gateway:${CONNECT_CCCEV_VERSION}
    container_name: cccev-gateway
    env_file:
      - .env_dev
    environment:
      - ssm_couchdb_url=${BCLAN_COUCH_URL}
      - ssm_couchdb_username=${BCLAN_COUCH_USER}
      - ssm_couchdb_password=${BCLAN_COUCH_PASS}
      - ssm_chaincode_url=${BCLAN_CHAINCODE_URL}
      - fs_url=http://fs-gateway:8090
      - spring_neo4j_uri=neo4j://cccev-neo4j:7687
      - spring_neo4j_authentication_username=neo4j
      - spring_neo4j_authentication_password=komunekomune
    labels:
      traefik.enable: "true"
      traefik.http.services.im-gateway.loadbalancer.server.port: ${CCCEV_PORT}
      traefik.http.routers.im-gateway.rule: Host(`${HOST_NAME_CONNECT}`) && PathPrefix(`/cccev`)
      traefik.http.routers.im-gateway.entrypoints: websecure
      traefik.http.routers.im-gateway.tls.certresolver: myresolver
      traefik.http.middlewares.test-stripprefix.stripprefix.prefixes: /cccev
      traefik.docker.network: ${DOCKER_NETWORK}
    restart: on-failure
    ports:
      - ${CCCEV_PORT}:8083
    networks:
      - net
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.5.0
    container_name: cccev-neo4j
    environment:
      - NEO4J_AUTH=neo4j/komunekomune
      - NEO4J_PLUGINS=["apoc"]
    networks:
      - net
    ports:
      - "7687:7687"
      - "7474:7474"  # browser interface (localhost:7474)

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
