services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${SECRET_MEILI_MASTER_KEY}
    volumes:
      -  meilisearch_data:/data.ms
    networks:
      - net
      -
  meilisearch-test:
    image: getmeili/meilisearch:latest
    container_name: meilisearch-test
    ports:
      - "7701:7700"
    environment:
      MEILI_MASTER_KEY: ${SECRET_MEILI_MASTER_KEY}
    volumes:
      -  meilisearch_data:/data.ms
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true

volumes:
  meilisearch_data:
