services:

  redis:
    image: redis/redis-stack:7.2.0-v13
    container_name: verr-redis
    env_file:
      - build/config/.env_dev
    environment:
      REDISEARCH_ARGS: MINPREFIX 1 MAXPREFIXEXPANSIONS 1000
    ports:
     - "127.0.0.1:6379:6379"
     - "127.0.0.1:8011:8001"
    networks:
      - net

#  redisinsight:
#    image: redislabs/redisinsight:latest
#    container_name: verrredisinsight
#    ports:
#       - "8001:8001"
#    networks:
#       - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
