services:

  im-keycloak:
    image: ${DOCKER_REPOSITORY}im-keycloak:${VERSION_IM}
    container_name: ${KC_HOSTNAME}
    environment:
      KC_DB_URL: 'jdbc:postgresql://${POSTGRES_HOSTNAME}/im-keycloak'
      KC_DB_PASSWORD: ${POSTGRES_USER}
      KC_DB_USERNAME: ${POSTGRES_PASS}
      KC_DB_SCHEMA: public
      KC_HOSTNAME: "${KC_HOST_URL}"
      KEYCLOAK_FRONTEND_URL: "${KC_HOST_URL}"
      KEYCLOAK_ADMIN: ${KC_ROOT_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ROOT_PASS}
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "ssl=false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - '8080:8080'
    networks:
      - net

  connect-fake-smtp:
    container_name: ${SMTP_HOST}
    image: reachfive/fake-smtp-server:latest
    ports:
      - "${SMTP_PORT}:1025"
      - "1080:1080"
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
