server:
  port: 8070

logging:
  level:
    root: INFO

spring:
  cloud:
    function:
      http:
        POST: project;data;control;identity
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tr-registry-postgres
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 10

cccev:
  url: http://localhost:8083

fs:
  url: http://localhost:8090

im:
  url: http://localhost:8009
  auth:
    url: http://im-keycloak:8080
    realm: registry-local
    clientId: tr-registry-script-api
    clientSecret: secret

f2:
  tenant:
    issuer-base-uri: http://im-keycloak:8080

platform:
  flag:
    module:
      control: false
      data: true
      project: false
      identity: false

  brevo:
    token: secret
    from: no-reply@kosm.io # TODO change
    contact-list: 4
    sandbox: false
    debug:
      enable: true
      email: test@kosm.io
---
spring:
  config:
    activate:
      on-profile: init

server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile: test

platform:
  brevo:
    sandbox: true

---
spring:
  config:
    activate:
      on-profile: local

platform:
  brevo:
    token: secret
    contact-list: 3
    debug:
      enable: true
      email: luc+wco2@kosm.io
