server:
  port: 8070

logging:
  level:
    root: INFO

spring:
  cloud:
    function:
      http:
        GET: about;flagGet
        POST: project;data;control;identity;config;global
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tr-registry-postgres
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30s

cccev:
  url: http://localhost:8083

fs:
  url: http://localhost:8090

im:
  url: http://localhost:8009
  auth:
    url: http://im-keycloak:8080
    realm: registry-local
    clientId: registry-platform-app
    clientSecret: secret

f2:
  tenant:
    issuer-base-uri: http://im-keycloak:8080

platform:
  ui:
    url: http://localhost:5173
    template:
      catalogue: ${platform.ui.url}/catalogues/{catalogueId}
  brevo:
    token: secret
    from: wikico2@kosm.io
    contact-list: 4
    sandbox: false
    debug:
      enable: true
      email: test@kosm.io
    template:
      charter: 1
  flag:
    module:
      control: true
      data: true
      project: true
      identity: true
  i18n:
    ordered-locales: en,fr,es
    catalogue:
      default-translation-type: translation
  identity:
    onboarding:
      default-roles:
        organization: rg_role_org_reader
        user: rg_role_user_admin
  meilisearch:
    url: http://localhost:7700
    secret: secret
  search:
    indexed-catalogue: 100m-solution,100m-sector,100m-system,100m-project,100m-planetary-boundary

---
spring:
  config:
    activate:
      on-profile: init

server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile: test

platform:
  brevo:
    sandbox: true

---
spring:
  config:
    activate:
      on-profile: local

platform:
  brevo:
    token: secret
    contact-list: 3
    sandbox: true
    debug:
      enable: true
      email: luc+wco2@kosm.io
