server:
  port: 8070

logging:
  level:
    root: INFO
    org.neo4j.ogm.drivers.bolt.response.BoltResponse: ERROR

spring:
  cloud:
    function:
      http:
        GET: about;flagGet
        POST: project;data;control;identity;config;global
  neo4j:
    uri: neo4j://localhost:7687
    authentication:
      username: neo4j
      password: komunekomune
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tr-registry-postgres
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30s

fs:
  url: http://localhost:8090

im:
  url: http://localhost:8009
  auth:
    url: http://im-keycloak:8080
    realm: registry-local
    clientId: registry-platform-app
    clientSecret: secret

f2:
  tenant:
    issuer-base-uri: http://im-keycloak:8080

platform:
  ui:
    url: http://localhost:5173
    template:
      catalogue: ${platform.ui.url}/catalogues/{catalogueId}
  brevo:
    token: secret
    from: wikico2@kosm.io
    contact-list: 4
    sandbox: false
    debug:
      enable: true
      email: test@kosm.io
    template:
      email-verified: 1
      catalogue-claim-ownership: 5
      onboarding-organization-conflict-user: 8
      onboarding-organization-conflict-orchestrator: 9
    support-email: test@kosm.io
  flag:
    module:
      control: true
      data: true
      project: true
      identity: true
  i18n:
    ordered-locales: en,fr,es
    catalogue:
      default-translation-type: translation
  identity:
    force-auth: false
    onboarding:
      default-roles:
        organization: rg_role_org_reader
        user: rg_role_user_admin
  meilisearch:
    url: http://localhost:7700
    secret: secret
  search:
    indexed-catalogue: organization, ecosystem
  catalogue:
    type-files: "classpath:catalogues"
  dataset:
    type-files: "classpath:datasets"

---
spring:
  config:
    activate:
      on-profile: init

server:
  port: 8000

---
spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      port: 6479
  neo4j:
    uri: neo4j://localhost:7688
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tr-registry-postgres-test

im:
  auth:
    realm: registry-test

fs:
  url: http://localhost:8091

platform:
  brevo:
    sandbox: true
  meilisearch:
    url: http://localhost:7701

---
spring:
  config:
    activate:
      on-profile: local

platform:
  brevo:
    token: secret
    contact-list: 3
    sandbox: false
    debug:
      enable: true
      email: luc+wco2@kosm.io
