# .github/workflows/deploy.yml
name: Deployment Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target deployment environment: dev, preprod, or prod'
        required: true
        type: string
      run_reset:
        description: 'Set to "true" to perform a reset (stack removal) before deployment (non-prod only)'
        required: false
        default: "false"
        type: string
    secrets:
      DOCKER_CONTEXT_SSH_KEY:
        required: true
      DOCKER_CONTEXT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      SECRET_MINIO_ROOT: ${{ secrets.SECRET_MINIO_ROOT }}
      SECRET_POSTGRES: ${{ secrets.SECRET_POSTGRES }}
      SECRET_KC_REALM_ROOT_CLIENT: ${{ secrets.SECRET_KC_REALM_ROOT_CLIENT }}
      SECRET_KC_ROOT_IM_CLIENT: ${{ secrets.SECRET_KC_ROOT_IM_CLIENT }}
      SECRET_KC_REGISTRY_SCRIPT_APP_CLIENT: ${{ secrets.SECRET_KC_REGISTRY_SCRIPT_APP_CLIENT }}
      SECRET_KC_APP_CLIENT: ${{ secrets.SECRET_KC_APP_CLIENT }}
      SECRET_REGISTRY_BREVO_TOKEN: ${{ secrets.SECRET_REGISTRY_BREVO_TOKEN }}
      SECRET_KC_ROOT_PASS: ${{ secrets.SECRET_KC_ROOT_PASS }}
      SECRET_KC_ADMIN_PASS: ${{ secrets.SECRET_KC_ADMIN_PASS }}
      SECRET_TRAEFIK_DASHBOARD_PASSWORD: ${{ secrets.SECRET_TRAEFIK_DASHBOARD_PASSWORD }}
      SECRET_MEILI_MASTER_KEY: ${{ secrets.SECRET_MEILI_MASTER_KEY }}
      PKG_GITHUB_USERNAME: ${{ github.actor }}
      PKG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOCKER_CONTEXT_SSH_KEY }}
      - name: Ensure Docker Context Exists
        shell: bash
        env:
          SERVER_IP: ${{ env.SERVER_IP }}
        run: |
          echo "Ensuring docker context 100m_${{ inputs.environment }} exists..."
          if ! docker context ls -q | grep -w "100m_${{ inputs.environment }}" ; then
            docker context create 100m_${{ inputs.environment }} --docker "${{ secrets.DOCKER_CONTEXT }}"
          fi
          docker context ls
      - name: Create Environment File
        shell: bash
        run: |
          echo "Creating environment file for ${{ inputs.environment }}..."
          cp infra/docker-compose/.env_dev_default infra/docker-compose/.env_dev_100m_${{ inputs.environment }}
          envsubst < infra/docker-compose/.env_dev_default > infra/docker-compose/.env_dev_100m_${{ inputs.environment }}
          cat infra/docker-compose/.env_dev_100m_${{ inputs.environment }}
      - name: Deploy Docker Services (Prod)
        shell: bash
        run: |
          echo "Deploying Docker services to Prod environment..."
          docker context use 100m_${{ inputs.environment }}
          make proxy deploy
          make connect deploy
          make connect-init deploy
          make registry deploy

  reset:
    if: ${{ inputs.environment == 'dev' || inputs.environment == 'preprod' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if Reset Is Enabled
        shell: bash
        run: |
          if [ "${{ inputs.run_reset }}" != "true" ]; then
            echo "Reset not enabled. Skipping reset step."
            exit 0
          fi
      - name: Reset Docker Stack
        shell: bash
        run: |
          echo "Resetting Docker stack for ${{ inputs.environment }} environment..."
          docker context use 100m_${{ inputs.environment }}
          docker stack rm registry-${{ inputs.environment }}-network || true
          docker volume rm registry-${{ inputs.environment }}-network_meilisearch_data registry-${{ inputs.environment }}-network_minio registry-${{ inputs.environment }}-network_postgres_data || true
