#name: Deployment Release
#
#on:
#  release:
#    types: [published]
#jobs:
#  deploy-preprod:
#    name: Deploy to ${{ github.event.inputs.environment }}
#    uses: deploy-workflow.yml
#    secrets:
#      DOCKER_CONTEXT_SSH_KEY: ${{ secrets.DOCKER_CONTEXT_SSH_KEY }}
#      DOCKER_CONTEXT: ${{ secrets.DOCKER_CONTEXT }}
#      SERVER_IP: ${{ secrets.SERVER_IP }}
#      SERVER_PORT: ${{ secrets.SERVER_PORT }}
#      SERVER_USER: ${{ secrets.SERVER_USER }}
#      SECRET_MINIO_ROOT: ${{ secrets.SECRET_MINIO_ROOT }}
#      SECRET_POSTGRES: ${{ secrets.SECRET_POSTGRES }}
#      SECRET_KC_REALM_ROOT_CLIENT: ${{ secrets.SECRET_KC_REALM_ROOT_CLIENT }}
#      SECRET_KC_ROOT_IM_CLIENT: ${{ secrets.SECRET_KC_ROOT_IM_CLIENT }}
#      SECRET_KC_REGISTRY_SCRIPT_APP_CLIENT: ${{ secrets.SECRET_KC_REGISTRY_SCRIPT_APP_CLIENT }}
#      SECRET_KC_APP_CLIENT: ${{ secrets.SECRET_KC_APP_CLIENT }}
#      SECRET_REGISTRY_BREVO_TOKEN: ${{ secrets.SECRET_REGISTRY_BREVO_TOKEN }}
#      SECRET_KC_ROOT_PASS: ${{ secrets.SECRET_KC_ROOT_PASS }}
#      SECRET_KC_ADMIN_PASS: ${{ secrets.SECRET_KC_ADMIN_PASS }}
#      SECRET_TRAEFIK_DASHBOARD_PASSWORD: ${{ secrets.SECRET_TRAEFIK_DASHBOARD_PASSWORD }}
#      SECRET_MEILI_MASTER_KEY: ${{ secrets.SECRET_MEILI_MASTER_KEY }}
#    with:
#      environment: preprod
#
#  deploy-prod:
#    needs: deploy-preprod
#    uses: deploy-workflow.yml
#    secrets:
#      DOCKER_CONTEXT_SSH_KEY: ${{ secrets.DOCKER_CONTEXT_SSH_KEY }}
#      DOCKER_CONTEXT: ${{ secrets.DOCKER_CONTEXT }}
#      SERVER_IP: ${{ secrets.SERVER_IP }}
#      SERVER_PORT: ${{ secrets.SERVER_PORT }}
#      SERVER_USER: ${{ secrets.SERVER_USER }}
#      SECRET_MINIO_ROOT: ${{ secrets.SECRET_MINIO_ROOT }}
#      SECRET_POSTGRES: ${{ secrets.SECRET_POSTGRES }}
#      SECRET_KC_REALM_ROOT_CLIENT: ${{ secrets.SECRET_KC_REALM_ROOT_CLIENT }}
#      SECRET_KC_ROOT_IM_CLIENT: ${{ secrets.SECRET_KC_ROOT_IM_CLIENT }}
#      SECRET_KC_REGISTRY_SCRIPT_APP_CLIENT: ${{ secrets.SECRET_KC_REGISTRY_SCRIPT_APP_CLIENT }}
#      SECRET_KC_APP_CLIENT: ${{ secrets.SECRET_KC_APP_CLIENT }}
#      SECRET_REGISTRY_BREVO_TOKEN: ${{ secrets.SECRET_REGISTRY_BREVO_TOKEN }}
#      SECRET_KC_ROOT_PASS: ${{ secrets.SECRET_KC_ROOT_PASS }}
#      SECRET_KC_ADMIN_PASS: ${{ secrets.SECRET_KC_ADMIN_PASS }}
#      SECRET_TRAEFIK_DASHBOARD_PASSWORD: ${{ secrets.SECRET_TRAEFIK_DASHBOARD_PASSWORD }}
#      SECRET_MEILI_MASTER_KEY: ${{ secrets.SECRET_MEILI_MASTER_KEY }}
#    with:
#      environment: prod
